### PR TITLE
Fix uninitialised values in unique for PooledDataArray

### LINKED ISSUE #265: #undef/uninitialised values from unique on PooledDataArray
Julia 0.6 and DataArrays v0.5.3 (also observed on Julia 0.5 and DataArrays v0.4.1)

If all elements in a level for a `PooledDataArray` are `NA`, then `unique` returns `#undef` for `String` elements and uninitialised values for `Int` elements. If only some of the elements for a level are `NA` (i.e. not all) then the issue is not observed.

### String
```julia
using DataArrays
x = PooledDataArray(["A", "B", "A"]);
masks = [[1], [2], [3], [1, 3]]
for mask in masks
    y = x[:]; y[mask] = NA
    @show mask
    display(unique(y))
    println()
end
```
gives:
```
mask = [1]
3-element DataArrays.DataArray{String,1}:
 NA
 "B"
 "A"

mask = [2]
3-element DataArrays.DataArray{String,1}:
    "A"
 #undef
 #undef

mask = [3]
3-element DataArrays.DataArray{String,1}:
 "A"
 "B"
 NA

mask = [1,3]
3-element DataArrays.DataArray{String,1}:
    NA
    "B"
 #undef
```

### Int
```julia
x = PooledDataArray([1, 2, 1]);
masks = [[1], [2], [3], [1, 3]]
for mask in masks
    y = x[:]; y[mask] = NA
    @show mask
    display(unique(y))
    println()
end
```
gives:
```julia
mask = [1]
3-element DataArrays.DataArray{Int64,1}:
  NA
 2
 1

mask = [2]
3-element DataArrays.DataArray{Int64,1}:
          1
 4492641712
 4491970448

mask = [3]
3-element DataArrays.DataArray{Int64,1}:
 1
 2
  NA

mask = [1, 3]
3-element DataArrays.DataArray{Int64,1}:
           NA
          2
 4491970448
```

### Version Info
```
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM)2 Duo CPU     P7550  @ 2.26GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Penryn)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, penryn)
```

### PR DESCRIPTION
**Pull request by joshbode**
Use the number of observed values (plus one for `NA`) to determine the
length of the result of `unique` on `PooledDataArrays`.

Fixes #265

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -3,6 +3,9 @@
 #
 
 using Base.Test
+if VERSION >= v"0.7.0-"
+    using FFTW
```
Comment (joshbode) [inline test/runtests.jl]: Added FFTW for `0.7.0-` since it has been removed from Base, however the nightly build image doesn't support it yet

Comment (nalimilan) [inline test/runtests.jl]: I would do `if !isdefined(Base, :FFTW)`, or check the exact commit when it was removed.

File: test/pooleddataarray.jl [hunk 2]
```diff
@@ -126,4 +126,13 @@
     r = vcat(ca1, ca2)
     @test r == vcat(a1, a2)
     @test isa(r, PooledDataArray{Int,DataArrays.DEFAULT_POOLED_REF_TYPE,4})
+
+    # Issue #265
```
Comment (nalimilan) [inline test/pooleddataarray.jl]: Would be nice to describe the issue in a few words.

File: src/pooleddataarray.jl [hunk 3]
```diff
@@ -334,7 +334,8 @@ function Base.unique{T}(pda::PooledDataArray{T})
     end
 
     if firstna > 0
-        res = DataArray(Vector{T}(nlevels + 1))
+        n = length(unique_values)
```
Comment (nalimilan) [inline src/pooleddataarray.jl]: Could define `n` earlier, since `length(unique_values)` is used above.

File: test/runtests.jl (hunk 1 above)
Comment (nalimilan) [inline test/runtests.jl]: Also, can you put this in a separate commit?

**Comment by nalimilan** [comment]
Thanks, looks good apart from the two minor points I highlighted.

File: src/pooleddataarray.jl (hunk 3 above)
Comment (joshbode) [inline src/pooleddataarray.jl]: Isn't `length(unique_values)` potentially still varying above?

File: test/runtests.jl (hunk 1 above)
Comment (joshbode) [inline test/runtests.jl]: Will do. Any thoughts on what should be done in [src/operators.jl](https://github.com/JuliaStats/DataArrays.jl/blob/master/src/operators.jl#L9)?

Comment (nalimilan) [inline test/runtests.jl]: Why not use the same check?

Comment (joshbode) [inline test/runtests.jl]: What if FFTW.jl isn't already imported?
(unless we make it a dependency, which I don't think is a good idea)

Comment (nalimilan) [inline test/runtests.jl]: I see. Let's ask @ararslan, but I would be inclined to deprecate this feature. People can convert to a standard array just like they need to do for any other external function.

Comment (ararslan) [inline test/runtests.jl]: Yeah, let's get rid of anything FFT-related in this package.

Comment (joshbode) [inline test/runtests.jl]: OK - my second commit should have got it all

Comment (ararslan) [inline test/runtests.jl]: Fantastic, thanks!
